jobs:
  build-jar:
    needs: delete-old-snapshot-assets
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build with Gradle
      run: .\gradlew.bat dist --no-daemon
    - continue-on-error: true
      name: Create Distribution
      run: distribution\create-distribution-jar.bat SNAPSHOT-$(date +"%Y%m%d_%H%M00")
    - continue-on-error: true
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ./distribution/freerouting-SNAPSHOT-*.jar
        release-tag: SNAPSHOT
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-macos-x64:
    needs: delete-old-snapshot-assets
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew dist
    - continue-on-error: true
      name: Create Distribution
      run: distribution/create-distribution-SNAPSHOT-macos-x64.sh SNAPSHOT-$(date
        +"%Y%m%d_%H%M00") "${{ secrets.APPLE_DEVELOPER_ID }}"
    - continue-on-error: true
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ./distribution/freerouting-SNAPSHOT-*-macos-x64.dmg
        release-tag: SNAPSHOT
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-ubuntu-x64:
    needs: delete-old-snapshot-assets
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew dist
    - continue-on-error: true
      name: Create Distribution
      run: distribution/create-distribution-linux-x64.sh SNAPSHOT-$(date +"%Y%m%d_%H%M00")
    - continue-on-error: true
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ./distribution/freerouting-SNAPSHOT-*-linux-x64.zip
        release-tag: SNAPSHOT
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-windows-x64:
    needs: delete-old-snapshot-assets
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build with Gradle
      run: .\gradlew.bat dist --no-daemon
    - continue-on-error: true
      name: Create Distribution
      run: distribution\create-distribution-SNAPSHOT-windows-x64.bat "SNAPSHOT-$(([datetime]::now).tostring("yyyyMMdd_HHmm00"))"
    - continue-on-error: true
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ./distribution/freerouting-SNAPSHOT-*-windows-x64.msi
        release-tag: SNAPSHOT
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  delete-old-snapshot-assets:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Delete old SNAPSHOT assets
      uses: mknejp/delete-release-assets@v1
      with:
        assets: "freerouting-SNAPSHOT.zip\nfreerouting-SNAPSHOT.tar.gz\nfreerouting-SNAPSHOT-*.*\
          \   \n"
        fail-if-no-assets: false
        tag: SNAPSHOT
        token: ${{ secrets.GITHUB_TOKEN }}
name: create-snapshot
on:
  repository_dispatch:
    types: trigger-ga___create-snapshot.yml
