jobs:
  build-jar:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build with Gradle
      run: .\gradlew.bat dist --no-daemon
    - continue-on-error: true
      id: tagName
      name: Get Tag name
      uses: olegtarasov/get-tag@v2.1
      with:
        tagRegex: v(.*)
        tagRegexGroup: 1
    - continue-on-error: true
      name: Create Distribution
      run: distribution\create-distribution-jar.bat ${{ steps.tagName.outputs.tag
        }}
    - continue-on-error: true
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ./distribution/freerouting-${{ steps.tagName.outputs.tag }}.jar
        release-tag: v${{ steps.tagName.outputs.tag }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-macos-x64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew dist
    - continue-on-error: true
      id: tagName
      name: Get Tag name
      uses: olegtarasov/get-tag@v2.1
      with:
        tagRegex: v(.*)
        tagRegexGroup: 1
    - continue-on-error: true
      name: Create Distribution
      run: distribution/create-distribution-macos-x64.sh ${{ steps.tagName.outputs.tag
        }}
    - continue-on-error: true
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ./distribution/freerouting-${{ steps.tagName.outputs.tag }}-macos-x64.dmg
        release-tag: v${{ steps.tagName.outputs.tag }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-ubuntu-x64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew dist
    - continue-on-error: true
      id: tagName
      name: Get Tag name
      uses: olegtarasov/get-tag@v2.1
      with:
        tagRegex: v(.*)
        tagRegexGroup: 1
    - continue-on-error: true
      name: Create Distribution
      run: distribution/create-distribution-linux-x64.sh ${{ steps.tagName.outputs.tag
        }}
    - continue-on-error: true
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ./distribution/freerouting-${{ steps.tagName.outputs.tag }}-linux-x64.zip
        release-tag: v${{ steps.tagName.outputs.tag }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  build-windows-x64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build with Gradle
      run: .\gradlew.bat dist --no-daemon
    - continue-on-error: true
      id: tagName
      name: Get Tag name
      uses: olegtarasov/get-tag@v2.1
      with:
        tagRegex: v(.*)
        tagRegexGroup: 1
    - continue-on-error: true
      name: Create Distribution
      run: distribution\create-distribution-windows-x64.bat ${{ steps.tagName.outputs.tag
        }}
    - continue-on-error: true
      uses: AButler/upload-release-assets@v3.0
      with:
        files: ./distribution/freerouting-${{ steps.tagName.outputs.tag }}-windows-x64.msi
        release-tag: v${{ steps.tagName.outputs.tag }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: create-release
on:
  repository_dispatch:
    types: trigger-ga___create-release.yml
