jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: no-issue-activity
        stale-issue-message: "Hey there!\U0001F44B This issue is stale because it\
          \ has been inactive for 60 days. If this matter is still relevant, feel\
          \ free to remove the stale label or add a comment. Otherwise, it will be\
          \ closed in 7 days. But remember, with thousands of monthly active users,\
          \ someone might just have the solution you need. This is a community-driven\
          \ project, and your active participation is crucial. If the issue is critical\
          \ for your work, consider contributing a fix yourself or hiring someone\
          \ to help. I'm here to support your efforts and will review and merge pull\
          \ requests as quickly as I can. Let's collaborate to keep improving our\
          \ project! \U0001F680 Your involvement is invaluable, and together, we can\
          \ ensure the continuous growth and success of our community. Thank you for\
          \ being an integral part of this journey. Your engagement is what drives\
          \ our project forward!"
        stale-pr-label: no-pr-activity
        stale-pr-message: This pull request is stale because it has been inactive
          for 60 days. Remove stale label or comment or this will be closed in 7 days.
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
